M48
; DRILL file KiCad 10.0.1 date 2026-04-20T15:04:34
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-04-20T15:04:34+05:30
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.200
%
G90
G05
T1
X80.0Y-65.0
X115.0Y-65.0
X120.0Y-160.0
X146.0Y-201.0
X153.0Y-65.0
X309.0Y-164.0
M30
